ARG source_repo
FROM ${source_repo}:base

ARG container_user
RUN test -n "${container_user}"

USER root

# Enable shell pipefail option
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

WORKDIR /tmp

RUN apt-get update -qq -y && apt-get install --no-install-recommends -qq -y \
        xvfb x11vnc xterm wmaker \
        astro-all topcat stilts man \
    && apt-get -y autoclean \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/*

ADD xinit.sh /usr/local/xinit.sh

RUN chmod 755 /usr/local/xinit.sh

ENV DISPLAY :10

WORKDIR /home/${container_user}

USER ${container_user}

EXPOSE 5910

ENTRYPOINT ["/usr/local/xinit.sh"]

